---
title: 'Blog Post number 1'
date: 2012-08-14
output: html_document
permalink: /posts/2012/08/blog-post-1/
tags:
  - cool posts
  - category1
  - category2
---
# Introduction

I provide here a replication in R of two important papers in the demand estimation literature. I use **BLPestimatoR**, a package created by Daniel Brunner to retrieve the original datasets from Berry Levinshon and Pakes (1995) and Nevo (2001)
```{r include = T, warning=FALSE, message = F}
rm(list = ls())
library(BLPestimatoR)
df1 <- productData_cereal
df2 <- productData_cars
summary(df1)
```

# General Model  

$T$ market indexed by $t = 1, \ldots , T$ \
$L_t$ consumers in each market \
$J+1$ products indexed by $j = 0, \ldots J$ \
$j=0$ is the outside option.

The conditional indirect utility is defined as:
$$
  u_{ijt} =\left\{
      \begin{aligned}
        &x_{jt} \beta_i + \alpha p_{jt} + \xi_{jt} + \epsilon_{ijt} & \quad \text{if} \quad & j \in \{1,\ldots,J\}\\
        &\epsilon_{i0t} & \quad \text{if} \quad & j = 0 \\
      \end{aligned}
    \right.
$$
 $x_{jt}$ is a $(1 \times K)$ vector of observed product characteristics \
$p_{jt}$ is the price ; $\alpha$ is the price valuation \
$\xi_{jt}$ is the unobserved product characteristic \
$\epsilon_{ijt}$ is the error term, usually iid RV with a type I EV distribution \
$\beta_i$ is a $(K\times 1)$ parameter vector of random coefficients \

The random coefficient for characteristic $k$ is given by:
$$
\beta_{i}^{k} = \beta^{k} + \theta^{k} v_{i}^{k}
$$

$\beta^{k}$ is a mean valuation for characteristic $k$ \
$v_{i}^{k}$ is a random variable \
$\theta^k$ is the standard deviation across consumers (if $\theta^k$ = 0 $\rightarrow$ Logit) \

Conditional indirect utility becomes:
$$
u_{ijt} = \underbrace{x_{jt} \beta - \alpha p_{jt} + \xi_{jt}}_{\delta_{jt}} \:+ \: \underbrace{\sum_{k} x_{jt}^{k} \, \theta^{k} \, v_{i}^{k}}_{\mu_{jt}(v_i)} \: + \: \epsilon_{ijt}
$$
